### ISSUE TITLE
Explain where to get resin

### ISSUE THREAD

**Issue by pfgithub** [roberttkahelin8/thingmajigs#12]
It doesn't say in the docs or in game (EMI loot doesn't exist for 1.20.4 neoforge), I had to check the source code to see that it's in the loot table for rubber tree leaves

**Comment by roberttkahelin8** [comment]
Ah yes! I completely forgot to update the docs and only the mod changelog itself really mentioned anything about rubber trees and such. Got pretty busy after some updates and forgot about the docs. They should be updated now.

Addons and utility mods aren't supported entirely (one note is the Converter block recipes aren't recipes so they won't show up at all as there is no functional way to do it), only some features require mods to be installed, otherwise said mods don't actually break the mod if not present.

Can't really support certain technical mods or give extra support on that end.

Another big note: NeoForge Thingamajigs works slightly different compared to Forge version so some features may act a bit different or better depending on version used and how many features NeoForge changes vs Forge. Also the source code needs a better way to be dumped here, but currently the setup i have breaks everything if i try to setup source control, so that's a bummer.

**Comment by roberttkahelin8** [comment]
Link to loot tables page here for future refs: [https://app.gitbook.com/o/Cn3VSbyeyS8PiygqwNlP/s/Ly9ZlxaUXoVDn3imWfry/items/items-from-loot-tables](https://app.gitbook.com/o/Cn3VSbyeyS8PiygqwNlP/s/Ly9ZlxaUXoVDn3imWfry/items/items-from-loot-tables)

**Comment by pfgithub** [comment]
What are the issues you're having using source control? I may be able to help
