### ISSUE TITLE
Some blocks/models may need to be retextured or redesigned

### ISSUE THREAD

**Issue by kazumadh** [roberttkahelin8/thingmajigs#18]
### Thanks you for having implemented my idea to your mod. However, there are some decoration objects that came from my ideas may need to be retextured or remodeled. Here's the list:
1. The steel block: The texture should be plain instead of striped. The old texture can be kept as a different block with different usage. 
2. The I-Beam: This should be preferentially redesigned. IRL its web isn't enormous like the model ingame. I suppose it need to be replaced with "**Composite I-Beam**". To simply put, it's an I-Beam with deck slab above (The deck slab can be concrete or steel grating). The texture of this steel beam should be the same as the retextured steel block. The old model can also be kept as a different block with different usage. Speaking of the height of this composite beam (deck included), it should be 1-block height (16 pixels) or 2-block height (32 pixels). The thickness of the deck slab should be 4 pixels and the remaining height of the I-beam will be 12 pixels or 28 pixels. The sizes of the I-beam will be given in the following:
-For 1-block height: 
Flange width = 4 pixels
Flange thickness = 0.5 pixel/1 flange
Web thickness = 0.5 pixel
-For 2-block height:
Flange width = 6 or 8 pixels
Flange thickness = 1 pixel/1 flange
Web thickness = 1 pixel
In real life those beams also have stiffeners and diaphragms. But it can be extremely complicated even it's just model design, so let's have conversation about these someday if you think so.
![composite beam](https://github.com/roberttkahelin8/thingmajigs/assets/140326816/98411468-d544-46cf-80b3-76a386a3d6c5)
3. The Steel Hoarding: The metal panel should be redesigned to have a feel of 16 x 16 pixels.
![2024-07-01_10 23 22](https://github.com/roberttkahelin8/thingmajigs/assets/140326816/797d1351-9b92-440b-85b5-6cadedc650c8)
4. The Curved Bridge Railing: The clear distance between the middle handrail and the lower one is too large (6 pixels = 375 mm, which is considered unsafe according to the AASHTO standard), it need one more handrail between those.
![2024-07-01_10 20 00](https://github.com/roberttkahelin8/thingmajigs/assets/140326816/ee59ae60-33bd-4890-8c17-3eb2663286d0)
**Looking forward to your response if there is something more to make clear.**

**Comment by roberttkahelin8** [comment]
I'm going to close this suggestion down due to an overwhelming amount of issues.

Although I appreciate your detailed, really cool ideas for features, the models and textures of blocks and items are at the lowest tier of the list, as I have no way of replicating real life objects in a minecraft-y, jappa-y form. Also, again, the mod _isn't about realism_, it just happens to have a lot of real objects in it, along with some _not so real objects_, for fun.

This means your suggested idea is on a list (a huge 100+ feature backlog), but probably is going to take a long time to implement because I can't hire someone do redo all my art and modeling (it's something I've wanted to do, but unfortunately I can't pay anyone nor have a good enough talent in pixel art to do it myself).
