### ISSUE TITLE
Can't add color to paint brush

### ISSUE THREAD

**Issue by Phasertokill** [roberttkahelin8/thingmajigs#20]
**Describe How, What and When It Happened**
I can't add paint to the paintbrush. I can't find any documentation on how to get it to work and simply adding the dye and brush to a crafting table doesn't work. Hopefully, I'm not oblivious and it's not a simple solution going over my head.

**How To Reproduce The Issue**
N/a

**The Expected Behavior**
Add the various dyes to the paintbrush.

**Screenshots Of The Issue**
N/a

**Version & OS (Please follow the formatting shown below):**
 - OS: Windows 10
 - Minecraft Version: 1.21
 - Mod Loader Version: NeoForge 21.0.146
 - Thingamajigs Neo Version 1.7.3

**Additional Info & Context**
It's probably some simple solution but I can't find docs on how to make it and Patchouli isn't updated yet to add the mod book.

Thanks in advance for your response and such a wonderful mod and abundance of decor!

**Comment by roberttkahelin8** [comment]
Thank you for the issue report and thanks for the compliments :D

I'm not sure if your aware (or if this was public enough) but some features in neo thingamajigs will be returning in an addon, which for paintbrushes doesn't exist yet. 

Also, bugs for neo thingamajigs (called Thingamajigs 2) should be reported to [Thingamajigs 2 GitHub](https://github.com/roberttkahelin8/thingamajigs2) instead of _this_ github to reduce confusion (which ironically, it seems more confusion was created by making a new GitHub for Thingamajigs 2).

Also Patchouli isn't in Thingamajigs Neo as it hasn't released for NeoForge at all yet, still waiting on that mod to update.

Keep an eye out for any "Thingamajigs 2 Addon" that adds road stuff back. The idea is to make the mod more modular for 1.21+. There is already an Addon out for Thingamajigs 2 called: "Thingamajigs 2: Goodies" which adds balloons and the converter plus some other old features back into the mod that don't exist in the base mod Thingamajigs 2.

Paintbrushes, roads, and some other things will return in a future addon when the time is right.

Hope this clears this confusion up.

Thank you for your bug report, and I'll close it now as "intended features and updates".
